#!/bin/bash
# Records Midi Data coming from a midi device

PORT="20:0"
FILENAME=$(date +%Y%m%d_%H%M%S).mid
PATH="${HOME}/Music/MadeByMe/Midi"

/usr/bin/arecordmidi -p $PORT $PATH/$FILENAME

echo "Wrote to $PATH/$FILENAME"
