#!/bin/bash

# Serves the current Working Directory in a Python Webserver Instance

if [[ -n $1 ]]; then
	python3 -m http.server $1 --bind 127.0.0.1
else
	python3 -m http.server 8000 --bind 127.0.0.1
fi
